{"name": "test_sub[Errortestcase]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 9", "trace": "self = <test_calc_shenjian.TestCalc object at 0x000002D5A492D070>, a = 5, b = 5, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(66, 22, 44), (-11, -19, 8), (-6, 9, -15), (8.5, 5.5, 3), (5, 5 , 9)],\n                             ids=(\"Posi\", \"Nega\", \"Posi&Nega\", \"Float\", \"Errortestcase\"))\n    # 使用fixture装饰器\n    @pytest.mark.usefixtures('testsub')\n    @pytest.mark.run(order=2)\n    def test_sub(self, a, b, expected):\n        result = self.calc.sub(a, b)\n>       assert result == expected\nE       assert 0 == 9\n\ntest_calc_shenjian.py:40: AssertionError"}, "attachments": [{"name": "stdout", "source": "9fbf8e9e-0a7e-4ea0-bae0-8659b3f84809-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "9"}], "start": 1609298012139, "stop": 1609298012139, "uuid": "90ec14bf-c88e-42e7-8b75-d80ab29289ce", "historyId": "32985474b767d07d669c9735e68efbfd", "testCaseId": "d7bd9313d11d97d7619ba0c19f6e34a8", "fullName": "test_calc_shenjian.TestCalc#test_sub", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('testsub')"}, {"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_calc_shenjian"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "HZCL2002"}, {"name": "thread", "value": "12744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_shenjian"}]}